# Generated by Django 3.0 on 2021-09-10 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=11, unique=True, verbose_name='document')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='phone')),
                ('role', models.CharField(choices=[('COMPANY', 'COMPANY'), ('USER', 'USER')], default='USER', max_length=200, verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
