# Generated by Django 3.0 on 2021-09-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='address',
            field=models.CharField(blank=True, help_text='fill in this field if the type of estate is urban', max_length=100, null=True, verbose_name='address'),
        ),
    ]
