# Generated by Django 3.0 on 2021-09-11 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210910_1905'),
        ('estates', '0002_auto_20210910_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersEstates',
            new_name='UserEstate',
        ),
    ]
