# Generated by Django 3.0 on 2021-09-11 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_auto_20210910_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='cadastral_id',
            new_name='catastral_id',
        ),
    ]
